name: az_health_care
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.4.2
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  bloc: ^9.0.0
  flutter_bloc: ^9.0.0
  conditional_builder_null_safety: ^0.0.6
  dio: ^5.8.0+1
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  shared_preferences: ^2.5.2
  webview_flutter: ^4.10.0
  connectivity_plus: 6.1.3
  fluttertoast: ^8.2.12
  lottie: ^2.6.0
  smooth_page_indicator: ^1.2.1
  carousel_slider: ^5.0.0
  skeletonizer: ^1.4.3


  photo_view: ^0.15.0
  dartz: ^0.10.1
  flutter_svg: ^2.2.0



dev_dependencies:
  flutter_launcher_icons: ^0.14.4




  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true


  assets:
    - assets/images/

  fonts:
    - family: jannah
      fonts:
        - asset: assets/fonts/jannah.ttf


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_main_icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/app_main_icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/app_main_icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/app_main_icon.png"