name: az_health_care
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  sqflite: ^2.4.2
  cupertino_icons: ^1.0.8
  intl: 0.19.0
  bloc: ^9.0.0
  flutter_bloc: ^9.0.0
  conditional_builder_null_safety: ^0.0.6
  dio: ^5.8.0+1
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  shared_preferences: ^2.5.2
  webview_flutter: ^4.10.0
#  connectivity_plus: 6.1.3
  fluttertoast: ^8.2.12
  lottie: ^2.6.0
  smooth_page_indicator: ^1.2.1
  carousel_slider: ^5.0.0
  skeletonizer: ^1.4.3
  file_picker: ^8.0.0+1
  connectivity_plus: ^5.0.2
  flutter_screenutil: ^5.9.3
  http: ^1.0.0
  path_provider: ^2.1.2
  device_info_plus: ^10.1.0
  flutter_local_notifications: ^17.0.0


  photo_view: ^0.15.0
  dartz: ^0.10.1
  flutter_svg: ^2.2.0
  flutter_blur: 0.0.2
  font_awesome_flutter: ^10.8.0
  line_icons: ^2.0.3
  icons_plus: ^5.0.0
  image_picker: ^1.1.2
#  flutter_local_notifications: ^17.2.3

#  sqflite: ^2.3.0
#  flutter_bloc: ^8.1.3
#  path: ^1.8.3
  pedometer: ^3.0.0
  permission_handler: ^11.0.1
  geolocator: ^9.0.2
#  intl: ^0.18.1
  fl_chart: ^0.65.0
  gap: ^3.0.1
#  flutter_foreground_task:
#    path: packages/flutter_foreground_task
#  android_intent_plus:
#    path: packages/android_intent_plus


#  flutter_foreground_task: ^5.0.0
#  android_intent_plus: ^3.0.1
#  flutter_local_notifications: ^19.3.0
#  permission_handler: ^12.0.1
#  timezone: ^0.9.4
#  flutter_native_timezone: ^2.0.0
#  timezone: ^0.10.1
#  flutter_native_timezone: ^2.0.0
#  timezone: ^0.9.2
#  permission_handler: ^11.0.1
dev_dependencies:
  flutter_launcher_icons: ^0.14.4




  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true


  assets:
    - assets/images/
#    - assets/texts/terms_conditions.txt

  fonts:
    - family: jannah
      fonts:
        - asset: assets/fonts/jannah.ttf


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_main_icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/app_main_icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/app_main_icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/app_main_icon.png"